### PR TITLE
Show extended error messages for snap builds with external link

### PR DESCRIPTION
**Pull request by maxiberta**
## Done

Show extended error messages for snap builds with external link, if available (fixes [LP: #1729580](https://bugs.launchpad.net/build.snapcraft.io/+bug/1729580)).

Launchpad is now able to expose a list of errors for each failed snap build in the `store_upload_error_messages` field (the old `store_upload_error_message` field, which joined all error messages ignoring any links, is still available for backwards compatibility). Each object in `store_upload_error_messages` contains a `message` field and an optional `link`, as reported by the reviewer tools via the Snap Store. See e.g. [this snap build in Launchpad](https://launchpad.net/~maxiberta/+snap/40315ffd245d9e29b06194c82e7aae29-xenial/+build/154794).

## QA

- Check out this feature branch
- Run the site using the command ```npm start -- --env=environments/dev.env```
- View the site locally in your web browser at: [http://0.0.0.0:8000/](http://0.0.0.0:8000/)
- Verify any previous failed builds show the error message as usual.
- Build a snap that fails (e.g. by setting `confinement: classic` in `snapcraft.yaml`).
- Verify the new failed build shows each error separately, with a link if available.

## Issue / Card

Fixes [Use of classic confinement mentions "the forum" without further explanation (LP: #1729580)](https://bugs.launchpad.net/build.snapcraft.io/+bug/1729580).

## Screenshots

Before:
screenshot-2018-2-23 build snapcraft io - maxiberta htop-snap-testing builds

After:
screenshot-2018-2-23 build snapcraft io - maxiberta htop-snap-testing builds

### CODE REVIEW

**Comment by bartaz** [comment]
@maxiberta Do you know if anything changed around launchpad people recently?
CI build started to fail with `FetchError: request to http://localhost:4000/launchpad/devel/people failed, reason: Nock: No match for request` - and it doesn't seem to be related to this PR. Also fails on master now.

I'll try to debug locally, but maybe you know more?

**Comment by maxiberta** [comment]
@bartaz, I'm unable to reproduce, `npm test` works fine locally. Is it possible to run CI again just in case it was a temporary failure?

**Comment by bartaz** [comment]
@maxiberta yep, works locally for me as well, but still fails on travis. 

I will have a look into what these failing tests are doing and why they may have started failing out of nowhere.

**Comment by bartaz** [comment]
@maxiberta I think I found the cause of the problem, will try to fix it tomorrow: #1063

**Comment by maxiberta** [comment]
Tests are passing now, thanks!

**Pull request merged**
