### PR TITLE
Showing build upload error message on build details

### LINKED ISSUE #714: "Built, failed to publish" doesn't explain why
screen shot 2017-05-04 at 08 28 23

When a build fails to publish there is no further explanation, and nothing suggests how you can resolve this (wait?).

### PR DESCRIPTION
**Pull request by bartaz**
## Done

Simple showing of build upload error message (as returned by API).

## QA

- Check out this feature branch
- Run the site using the command ```npm start -- --env=environments/dev.env```
- View the site locally in your web browser at: [http://0.0.0.0:8000/](http://0.0.0.0:8000/)
- Add a snap that builds but fails to publish
- Go the the build page

## Issue / Card

Fixes #714 

## Screenshots

screen shot 2017-08-21 at 11 29 14

### CODE REVIEW

**Comment by richmccartney** [comment]
@bartaz I've pulled the branch downa nd I have a failing build, but I am not getting the error 🤔 Anything I am doing wrong to show the error?

https://cl.ly/0I1U072y210H

**Comment by bartaz** [comment]
@richmccartney Hmm.. Weird, I forked your repo but for me it built and released just fine:
screen shot 2017-08-22 at 15 40 33

Would need to dig into redux data (and/or network API response) to see what build status your build has.

**Comment by richmccartney** [comment]
@bartaz Following state doesn't show an error message - storeUploadStatus(pin): "Failed to release to channels"

**Comment by kwm14** [comment]
@bartaz @richmccartney 

Regarding your design update to 'Build failed release' section I'm not sure on the user interaction here but;

- if it's a prompt to the user we should be using our [Notification](https://docs.vanillaframework.io/en/patterns/notification) pattern and in this instance it should use `.p-notification--negative`
- but if it's an input field a user types invalid info we should be using our [Forms](https://docs.vanillaframework.io/en/base/forms) pattern applying `.is-error` validation class

**Comment by matthewpaulthomas** [comment]
The release error is not a prompt to the user and it is not an input field. If it looks like either of those things, we should fix the visual design so that it doesn’t. But I don’t think that should block merging this.

The release error is not a notification for the same reasons that the build log is not a notification: it is information about the results of the build, it is not interactive at all, and it does not disappear (either manually or automatically) like a notification does. It should be shown whenever you look at that build page, even weeks or months later.

**Comment by bartaz** [comment]
@kwm14 @matthewpaulthomas Thanks for comments.

Yes, this is not a prompt or notification. So in this sense notification pattern may not be the best choice.

I can add an error icon to this, to make it more clear that it's an error 'message' and make it look less like an input field:

screen shot 2017-08-23 at 09 53 33

**Comment by kwm14** [comment]
@bartaz @matthewpaulthomas 

If your suggesting that it's not a notification or input field then we can't apply a mix of styles to solve the solution here. We can't just create a new pattern for this use case.

As you mention it's a error 'message' so in this case it should use our notification pattern whether it's an error, warning or informative message. This negative variant should be used to convey information that is critical (error) and the user should take action (in this case you can remove the CTA from the notification.

**Comment by bartaz** [comment]
@kwm @matthewpaulthomas @richmccartney 

Using notification pattern it would be like this:

screen shot 2017-08-23 at 11 09 02

**Comment by kwm14** [comment]
@bartaz looking good! Thanks

**Comment by richmccartney** [comment]
Looks great @bartaz +1

**Comment by evandandrea** [comment]
Star; thank you for this!

**Pull request merged**
